---
name: on_hello_event1
pack: hello_dv
description: Sample rule firing on hello_dv.event1.
enabled: true
trigger:
    type: hello_dv.event1
action:
    ref: hello_dv.greet
    parameters:
        greeting: Yo
